# Generated by Django 4.2.8 on 2023-12-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_alter_doctor_doc_pic_appointmet'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
