# Generated by Django 4.2.8 on 2023-12-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Type_query',
        ),
    ]
